# Generated by Django 2.2.5 on 2020-07-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200708_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='istant_book',
            new_name='instant_book',
        ),
    ]
