# Generated by Django 2.2.5 on 2020-07-12 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messeage',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messeage',
            new_name='message',
        ),
    ]
